# Generated by Django 5.1.7 on 2025-03-20 13:07

from django.db import migrations


def add_categories(apps, schema_editor):
    Category = apps.get_model('jobapp', 'Category')
    Category.objects.create(name="Software Development")
    Category.objects.create(name="Marketing")
    Category.objects.create(name="Design")
    Category.objects.create(name="Finance")
    Category.objects.create(name="Human Resources")
    Category.objects.create(name="Information Technology")
    Category.objects.create(name="Other")

class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_applicant_id_alter_bookmarkjob_id_and_more'),
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
