# Generated by Django 5.1.7 on 2025-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_auto_20250320_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
